package com.flashys.flashys_backend.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.geo.GeoJsonPoint;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "artist")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class Artist {

    @Id
    private String artistId; // MongoDB will generate this as an autogenerated ID

    private String displayName;
    private String pronouns;
    private GeoJsonPoint location; // Store location as a GeoJsonPoint
    private String bio;
    private String link;
    private String profilePic; // Store as a Base64 encoded string
    private String email;
    private String password;

    public Artist(String displayName, String pronouns, GeoJsonPoint location, String bio, String link, String profilePic, String email, String password) {
        this.displayName = displayName;
        this.pronouns = pronouns;
        this.location = location;
        this.bio = bio;
        this.link = link;
        this.profilePic = profilePic;
        this.email = email;
        this.password = password;
    }

    // Constructors, additional methods, and any other annotations can be added here.

    // You can generate getters and setters using Lombok's @Getter and @Setter annotations if needed.
}